version: '3'
services:
  minecraft:
    container_name: minecraft-server
    image: itzg/minecraft-server
    restart: 'unless-stopped'
    ports:
      - '25565:25565'
      - '8123:8123'
    environment:
      EULA: 'TRUE'
      DIFFICULTY: 'normal'

      # ADMINS
      OPS: Trobleton

      # PLAYER SETTINGS
      MAX_PLAYERS: 24

      # SERVER CONFIG
      MEMORY: '2G'
    volumes: 
      - ./temp_data:/data
    tty: true
    stdin_open: true